### ISSUE TITLE
Include Prometheus metrics 

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/terraform-seqera-eks#17]
Seqera Platform HPA scaling policy relies on Prometheus metrics to scale pods on-demand depending the number of http requests. See here

```
  - type: Pods
    pods:
      metric:
        name: http_server_requests
      target:
        type: AverageValue
        averageValue: '150'
```

This requires the deployment of the Prometheus service along with the other components of the Seqera Platform. Ideally this should be an optional step in the Terraform module.
